global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ldap-load-balancer"
    static_configs:
      - targets: ["ldap-load-balancer:9090"]
    metrics_path: /metrics
